### ISSUE TITLE
how to open this json in web browser or how to convert it into an image?

### ISSUE THREAD

**Issue by rajputs37** [a3ng7n/Altium-Schematic-Parser#10]

**Comment by a3ng7n** [comment]
It outputs json files containing circuit netlist information. If you want to re-convert back into a schematic I think the best approach would be either a.) getting a copy of altium, or another ee cad program to convert the schdoc for you, or b.) use something like https://github.com/nturley/netlistsvg note: the json from this parser outputs isn't natively compatible with netlistsvg, but it wouldn't be too hard to write a converter on your own.
